Repository overte-org/community-apps, pull requests merged in 2023-08, with the labels that each got.

#31 Adds APPRECIATE Application
  applications/appreciate/README.md
  applications/appreciate/appreciate.jpg
  applications/appreciate/appreciate_app.js
  applications/appreciate/resources/animations/Cheering.fbx
  applications/appreciate/resources/animations/Clapping.fbx
  applications/appreciate/resources/appreciate_ui.html
  applications/appreciate/resources/css/Raleway-Regular.ttf
  applications/appreciate/resources/css/Raleway.license
  applications/appreciate/resources/css/style.css
  applications/appreciate/resources/images/hueBar.jpg
  applications/appreciate/resources/images/icons/appreciate-a.svg
  applications/appreciate/resources/images/icons/appreciate-i.svg
  applications/appreciate/resources/images/loadingSpinner.svg
  applications/appreciate/resources/js/appreciate_ui.js
  applications/appreciate/resources/sounds/claps/01.wav
  applications/appreciate/resources/sounds/claps/02.wav
  applications/appreciate/resources/sounds/claps/03.wav
  applications/appreciate/resources/sounds/claps/04.wav
  applications/appreciate/resources/sounds/claps/05.wav
  applications/appreciate/resources/sounds/claps/06.wav
  applications/appreciate/resources/sounds/claps/07.wav
  applications/appreciate/resources/sounds/claps/08.wav
  applications/appreciate/resources/sounds/claps/09.wav
  applications/appreciate/resources/sounds/claps/10.wav
  applications/appreciate/resources/sounds/claps/11.wav
  applications/appreciate/resources/sounds/claps/12.wav
  applications/appreciate/resources/sounds/claps/13.wav
  applications/appreciate/resources/sounds/claps/14.wav
  applications/appreciate/resources/sounds/claps/15.wav
  applications/appreciate/resources/sounds/claps/16.wav
  applications/appreciate/resources/sounds/whistles/01.wav
  applications/appreciate/resources/sounds/whistles/02.wav
  applications/appreciate/resources/sounds/whistles/03.wav
  applications/appreciate/resources/sounds/whistles/04.wav
  applications/appreciate/resources/sounds/whistles/05.wav
  applications/appreciate/resources/sounds/whistles/06.wav
  applications/appreciate/resources/sounds/whistles/07.wav
  applications/appreciate/resources/sounds/whistles/08.wav
  applications/appreciate/resources/sounds/whistles/09.wav
  applications/appreciate/resources/sounds/whistles/10.wav
  applications/appreciate/resources/sounds/whistles/11.wav
  applications/appreciate/resources/sounds/whistles/12.wav
  applications/appreciate/resources/sounds/whistles/13.wav
  applications/appreciate/resources/sounds/whistles/14.wav
  applications/appreciate/resources/sounds/whistles/15.wav
  applications/appreciate/resources/sounds/whistles/16.wav
  applications/appreciate/resources/sounds/whistles/17.wav
  applications/metadata.js
Labels: QA approved, dev completed

#32 Home App: Change the fallback to tutorial rather than localhost
  applications/home/app_home.js
Labels: CR approved, dev completed

#33 Add the "ScaleMe" app
  applications/metadata.js
  applications/scaleMe/icons/active.png
  applications/scaleMe/icons/inactive.png
  applications/scaleMe/index.html
  applications/scaleMe/scaleMe.js
Labels: CR approved
