Repository overte-org/community-apps, pull requests merged in 2024-03, with the labels that each got.

#74 'Domain Mapper' Application
  applications/domainMapper/app-domainMapper.js
  applications/domainMapper/icon_active.png
  applications/domainMapper/icon_inactive_green.png
  applications/domainMapper/icon_inactive_white.png
  applications/metadata.js
Labels: needs CR, needs QA, dev completed

#73 Fly Avatar app: Fix when the Fly Avatar is present at closure.
  applications/flyAvatar/app-flyAvatar.js
Labels: dev completed

#72 Nametag shadow removal
  applications/nametags/nametags.js
Labels: CR approved
