Repository overte-org/community-apps, pull requests merged in 2025-01, with the labels that each got.

#99 Fix nametag positions
  applications/metadata.js
  applications/nametags/nametags.js
Labels: enhancement, CR approved, QA approved

#93 Add FlowAppCpp.js.
  applications/flow/flow-a.svg
  applications/flow/flow-i.svg
  applications/flow/flowAppCpp.html
  applications/flow/flowAppCpp.js
  applications/flow/polylineTexture.png
  applications/metadata.js
Labels: enhancement, CR approved

#101 Add Blendshape Buddy app
  applications/flex/blendshape_buddy.html
  applications/flex/blendshape_buddy.js
  applications/flex/flex-a.svg
  applications/flex/flex-i.svg
  applications/metadata.js
Labels: needs CR
